language: python
python:
- 2.7
- 3.4
- 3.5
- pypy
- pypy3
before_install:
  - pip install flake8
  - pip install coveralls

script:
  - flake8 grazer
  - python setup.py test

after_success:
  - coveralls
